import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { CartProvider } from "@/components/CartContext";
import QueryProvider from "../components/QueryProvider";
import Providers from "./providers";
import { WishlistProvider } from "@/components/WishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
        <Providers>
          <QueryProvider>
            <WishlistProvider>
              <CartProvider>
                <Navbar />
                <main className="container mx-auto px-4 py-8">{children}</main>
                <Footer />
              </CartProvider>
            </WishlistProvider>
          </QueryProvider>
        </Providers>
      </body>
    </html>
  );
}
